(TeX-add-style-hook "TIR"
 (lambda ()
    (LaTeX-add-labels
     "sec-1"
     "sec-2"
     "sec-3"
     "sec-3-1"
     "sec-3-1-1"
     "sec-3-1-2"
     "sec-3-1-3"
     "sec-3-1-4"
     "sec-3-1-5"
     "sec-3-2"
     "sec-3-3")
    (TeX-run-style-hooks
     "hyperref"
     "amssymb"
     "wasysym"
     "marvosym"
     "textcomp"
     "amsmath"
     "ulem"
     "normalem"
     "rotating"
     "wrapfig"
     "float"
     "longtable"
     "graphicx"
     "fixltx2e"
     "fontenc"
     "T1"
     "inputenc"
     "utf8"
     "latex2e"
     "scrartcl10"
     "scrartcl"
     "")))

